name: Docker Repo [ ci-build-env ] Active Update Push

on:
  # This workflow only runs when triggered by a push event
  push:
    # Only runs when take push events on master branch
    branches: [ master ]
    # Only runs take push changes Dockerfile inside ci-build-env folder
    paths:
      - 'ci-build-env/*/Dockerfile'

env:
  DOCKER_NAME: ci-build-env

jobs:

  TAG_gcc-arm:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: gcc-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_NAME}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: echo TBD Implement push function for ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}


  TAG_armc6:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: armc6
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_NAME}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: echo TBD Implement push function for ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}

