name: Docker repo ci-build-env PR Check

on:
  pull_request:
    branches: [ master ]

jobs:
  

  TAG_gcc-arm:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: gcc-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image with tag $TAG_NAME
      run: docker build ci-build-env/$TAG_NAME/ --tag ci-build-env:$TAG_NAME
    - name: Test image tag $TAG_NAME
      run: |
        docker run --rm ci-build-env:$TAG_NAME cat env_settings
        docker run --rm ci-build-env:$TAG_NAME ./env_tests.sh


  TAG_gcc-arm:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: armc6
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image with tag $TAG_NAME
      run: docker build ci-build-env/$TAG_NAME/ --tag ci-build-env:$TAG_NAME
    - name: Test image tag $TAG_NAME
      run: |
        docker run --rm ci-build-env:$TAG_NAME cat env_settings
        docker run --rm ci-build-env:$TAG_NAME ./env_tests.sh

