name: Docker repo ci-test-env Active Update Push

on:
  # This workflow only runs when triggered by a push event
  push:
    # Only runs when take push events on master branch
    branches: [ master ]
    # Only runs take push changes Dockerfile inside ci-test-env folder
    paths:
      - 'ci-test-env/*/Dockerfile'

jobs:

  TAG_greentea:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: greentea
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image tag <$TAG_NAME>
      run: docker build ci-test-env/$TAG_NAME/ --tag ci-test-env:$TAG_NAME
    - name: Push image tag <$TAG_NAME> to remote
      run: echo TBD Implement push function $TAG_NAME


  TAG_zephyr:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: zephyr
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image tag <$TAG_NAME>
      run: docker build ci-test-env/$TAG_NAME/ --tag ci-build-env:$TAG_NAME
    - name: Push image tag <$TAG_NAME> to remote
      run: echo TBD Implement push function $TAG_NAME

