name: [ ci-test-env ] Passive Update

on:
  schedule:
    # Triggers This job at every Sunday 9am
    - cron:  '0 9 * * 6'
  # Accept manual triggers
  workflow_dispatch:

env:
  DOCKER_NAME: ci-test-env

jobs:

  TAG-greentea:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: greentea
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_NAME}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
    - name: Show tools installed
      run: docker run --rm ${{env.DOCKER_NAME}}:${{env.TAG_NAME}} cat env_settings
    - name: Test Docker image
      run: docker run --rm ${{env.DOCKER_NAME}}:${{env.TAG_NAME}} ./env_test.sh
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: echo TBD Implement push function for ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}

  TAG-zephyr:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: zephyr
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}
      run: docker build ${{env.TAG_NAME}}/${{env.TAG_NAME}}/ --tag ${{env.TAG_NAME}}:${{env.TAG_NAME}}
    - name: Show tools installed
      run: docker run --rm ${{env.DOCKER_NAME}}:${{env.TAG_NAME}} cat env_settings
    - name: Test Docker image
      run: docker run --rm ${{env.DOCKER_NAME}}:${{env.TAG_NAME}} ./env_test.sh
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: echo TBD Implement push function for ${{env.DOCKER_NAME}}:${{env.TAG_NAME}}

