name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image ci-build-env-exp:cmake3.18
      run: docker build docker-hub-exp/ci-build-env-exp/cmake3.18/ --tag local-ci-build-env-exp:cmake3.18
    - name: Build Docker image ci-build-env-exp:cmake3.20
      run: docker build docker-hub-exp/ci-build-env-exp/cmake3.20/ --tag local-ci-build-env-exp:cmake3.20
